---
- name: Install Cockpit and Pacemaker on Ubuntu nodes
  hosts: nodes
  become: true
  become_user: root

  tasks:
    - name: Install Cockpit package
      apt:
        name: cockpit
        state: present
        update_cache: yes

    - name: Install Pacemaker and Corosync packages
      apt:
        name:
          - pacemaker
          - corosync
          - crmsh  # CRM shell for managing Pacemaker
        state: present
        update_cache: yes

    - name: Ensure Cockpit service is started and enabled
      systemd:
        name: cockpit
        state: started
        enabled: true

    - name: Ensure Pacemaker service is started and enabled
      systemd:
        name: pacemaker
        state: started
        enabled: true

    - name: Ensure Corosync service is started and enabled
      systemd:
        name: corosync
        state: started
        enabled: true

    - name: Open Cockpit port (9090) in the firewall (UFW)
      ufw:
        rule: allow
        name: 'Cockpit'
        state: enabled
      when: ansible_facts['ansible_os_family'] == 'Debian'
