---
- name: Update and upgrade Ubuntu servers
  hosts: nodes
  become: yes
  tasks:

    - name: Update APT package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to latest version
      apt:
        upgrade: dist

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes

    - name: Autoclean local repository of retrieved package files
      apt:
        autoclean: yes
- name: Wait for apt lock to be released
  shell: |
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
      sleep 5
    done
  changed_when: false
