---
- name: Update and upgrade packages on nodes
  hosts: nodes  # Target the 'nodes' group defined in your inventory
  become: true  # Use sudo to escalate privileges
  become_user: root  # Run as root after sudo

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
