---
- name: Update and upgrade packages on target hosts
  hosts: nodes
  become: true
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Only update if older than 1 hour

    - name: Upgrade all packages
      apt:
        upgrade: dist
